[theme]
base="light"
primaryColor="#3B82F6"     # bleu
backgroundColor="#9eb8d3ff"  # fond gris clair
secondaryBackgroundColor="#5fa2adff" # cartes/blocs
textColor="#ffffffff"        # texte noir
font="free-serif"
