[theme]
base="light"
primaryColor="#1f77b4"     # bleu
backgroundColor="#3a47433d"  # fond gris clair
secondaryBackgroundColor="#225544ff" # cartes/blocs
textColor="#000000"        # texte noir
font="sans serif"
