[theme]
base="light"
primaryColor="#3B82F6"     # bleu
backgroundColor="#F8F9FA"  # fond gris clair
secondaryBackgroundColor="#225544ff" # cartes/blocs
textColor="#2C3E50"        # texte noir
font="sans serif"
