[theme]
base="light"
primaryColor="#1f77b4"     # bleu
backgroundColor="#f5f5f5"  # fond gris clair
secondaryBackgroundColor="#ffffff" # cartes/blocs
textColor="#000000"        # texte noir
font="sans serif"
